---

# ---- HHVM repository configuration ----

# HHVM keyserver fingerprint
hhvm_keyserver_fingerprint: '0x5a16e7281be7a449'

# Whether to monitor the HHVM process using monit
hhvm_monit: False

# ---- HHVM configuration ----

# HHVM php.ini settings
hhvm_php_settings:
  'log.level': 'Warning'
  'log.always_log_unhandled_exceptions': 'true'
  'log.runtime_error_reporting_level': '8191'
  'mysql.typed_results': 'false'

# HHVM server.ini settings
hhvm_server_settings:
  'header': 'true'
  'log.use_log_file': 'true'
  'log.file': '/var/log/hhvm/error.log'
  'repo.central.path': '{{ hhvm_hhbc }}'
  'server.default_document': 'index.php'
  'server.file_socket': '{{ hhvm_sock }}'
  'server.type': 'fastcgi'
