---
# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# -------------------
#   HHVM repository configuration ----
# -------------------

# .. envvar:: hhvm_upstream_key
#
# APT GPG key fingerprint used to sign the upstream HHVM packages.
hhvm_upstream_key: '36AEF64D0207E7EEE352D4875A16E7281BE7A449'

# .. envvar:: hhvm_upstream_repository
#
# Address of the HHVM upstream APT repository.
hhvm_upstream_repository: 'deb http://dl.hhvm.com/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} main'


# -------------------
#   HHVM configuration
# -------------------

# .. envvar:: hhvm_file_post_max_size
#
# Max size of POST requests.
hhvm_file_post_max_size: '8M'

# .. envvar:: hhvm_file_upload_max_filesize
#
# Max file upload size.
hhvm_file_upload_max_filesize: '{{ hhvm_file_post_max_size }}'

# .. envvar:: hhvm_jit_cold_size
#
# Size of cold code cache. Code that is unlikely to be executed is deemed cold.
hhvm_jit_cold_size: '{{ 0.5 * hhvm_jit_size | int }}'

# .. envvar:: hhvm_jit_frozen_size
#
# Size of extremely cold code cache. Code that is almost never executed, or executed
# once and then freed up, is deemed frozen.
hhvm_jit_frozen_size: '{{ hhvm_jit_size }}'

# .. envvar:: hhvm_jit_max_usage
#
# Maximum amount of code to generate.
hhvm_jit_max_usage: '{{ hhvm_jit_size }}'

# .. envvar:: hhvm_jit_size
#
# Size in bytes of main translation cache.
hhvm_jit_size: 62914560

# .. envvar:: hhvm_php_extra
#
# Extra configuration options at the end of the HHVM php.ini file.
hhvm_php_extra: ''

# .. envvar:: hhvm_php_settings
#
# Dict of HHVM php.ini settings.
hhvm_php_settings:
  'log.level': 'Warning'
  'log.always_log_unhandled_exceptions': 'true'
  'log.runtime_error_reporting_level': '8191'
  'mysql.typed_results': 'false'

# .. envvar:: hhvm_server_extra
#
# Extra configuration options at the end of the HHVM server.ini file.
hhvm_server_extra: ''

# .. envvar:: hhvm_server_settings
#
# Dict of HHVM server.ini settings.
hhvm_server_settings:
  'header': 'true'
  'jit_a_size': '{{ hhvm_jit_size }}'
  'jit_a_cold_size': '{{ hhvm_jit_cold_size }}'
  'jit_a_frozen_size': '{{ hhvm_jit_frozen_size }}'
  'jit_a_max_usage': '{{ hhvm_jit_max_usage }}'
  'log.use_log_file': 'true'
  'log.file': '/var/log/hhvm/error.log'
  'repo.central.path': '{{ hhvm_hhbc }}'
  'server.default_document': 'index.php'
  'server.file_socket': '{{ hhvm_sock }}'
  'server.type': 'fastcgi'
  'server.user': '{{ hhvm_server_user }}'

# .. envvar:: hhvm_server_user
#
# User that HHVM runs under.
hhvm_server_user: ''
