---
# Default variables
# =================

# .. contents:: Sections
#    :local:
#
# ---------------------------
#   wp-cli configuration
# ---------------------------

# .. envvar:: wpcli_base_url
#
# Base URL where the wp-cli program is downloaded from.
wpcli_base_url: 'https://raw.githubusercontent.com/wp-cli/builds/gh-pages'


# .. envvar:: wpcli_src_dir
#
# wp-cli sources root directory.
wpcli_src_dir: '{{ (ansible_local.root.src
                         if (ansible_local|d() and ansible_local.root|d() and
                             ansible_local.root.src|d())
                         else "/usr/local/src") + "/wpcli" }}'
