---

# --------------------------
#   Fail2ban configuration
# --------------------------

wordpress_fail2ban_action_permanent_ban:
  name: 'wordpress-permanent'
  start: cat /etc/fail2ban/wordpress-banlist.<name> | while read IP; do ip route list | grep -q "unreachable $IP" || ip route add unreachable $IP; done
  stop: touch /etc/fail2ban/wordpress-banlist.<name>
  check: test -e /etc/fail2ban/wordpress-banlist.<name>
  ban: |
    FILE=/etc/fail2ban/wordpress-banlist.<name>
    grep -q "<ip>" "$FILE" || ip route list | grep -q 'unreachable <ip>' || ip route add unreachable <ip>
    grep -q "<ip>" "$FILE" || echo "<ip>" >> "$FILE"

wordpress_fail2ban_filter_ddos:
  name: 'wordpress-ddos'
  failregex: '^<HOST> .* "(GET|POST)'

wordpress_fail2ban_filter_login:
  name: 'wordpress-login'
  failregex: '^<HOST> .* "POST .*?/(wp-login|xmlrpc).php'

wordpress_fail2ban_filter_repeat_bans:
  name: 'wordpress-repeat-bans'
  failregex: 'fail2ban\.actions:\s+WARNING\s+\[(?:.*)\]\s+Ban\s+<HOST>'
  ignoreregex: 'fail2ban\.actions:\s+WARNING\s+\[wordpress-permanent\]\s+Ban\s+<HOST>'

wordpress_fail2ban_jail_badbots:
  name: 'wordpress-badbots'
  enabled: '{{ wordpress_fail2ban_jail_badbots_enabled }}'
  action: '{{ wordpress_fail2ban_jail_badbots_action }}'
  filter: 'apache-badbots'
  port: 'http,https'
  logpath: '/var/log/nginx/varnish*access.log'
  find: '{{ wordpress_fail2ban_jail_badbots_findtime }}'
  maxretry: '{{ wordpress_fail2ban_jail_badbots_maxretry }}'
  bantime: '{{ wordpress_fail2ban_jail_badbots_bantime }}'

wordpress_fail2ban_jail_ddos:
  name: 'wordpress-ddos'
  enabled: '{{ wordpress_fail2ban_jail_ddos_enabled }}'
  action: '{{ wordpress_fail2ban_jail_ddos_action }}'
  filter: 'wordpress-ddos'
  port: 'http,https'
  logpath: '/var/log/nginx/varnish*access.log'
  find: '{{ wordpress_fail2ban_jail_ddos_findtime }}'
  maxretry: '{{ wordpress_fail2ban_jail_ddos_maxretry }}'
  bantime: '{{ wordpress_fail2ban_jail_ddos_bantime }}'

wordpress_fail2ban_jail_login:
  name: 'wordpress-login'
  enabled: '{{ wordpress_fail2ban_jail_login_enabled }}'
  action: '{{ wordpress_fail2ban_jail_login_action }}'
  filter: 'wordpress-login'
  port: 'http,https'
  logpath: '/var/log/nginx/varnish*access.log'
  find: '{{ wordpress_fail2ban_jail_login_findtime }}'
  maxretry: '{{ wordpress_fail2ban_jail_login_maxretry }}'
  bantime: '{{ wordpress_fail2ban_jail_login_bantime }}'

wordpress_fail2ban_jail_permanent:
  name: 'wordpress-permanent'
  enabled: '{{ wordpress_fail2ban_jail_permanent_enabled }}'
  action: '{{ wordpress_fail2ban_jail_permanent_action }}'
  filter: 'wordpress-repeat-bans'
  logpath: '/var/log/fail2ban.log'
  find: '{{ wordpress_fail2ban_jail_permanent_findtime }}'
  maxretry: '{{ wordpress_fail2ban_jail_permanent_maxretry }}'
  bantime: '-1'

# --------------------------
#   MariaDB configuration
# --------------------------

wordpress_mariadb_database:
  name: '{{ wordpress_database_name }}'

wordpress_mariadb_user:
  name: '{{ wordpress_database_user }}'
  password: '{{ wordpress_database_password }}'
  host: '{{ wordpress_mariadb_client }}'
  priv: '{{ wordpress_database_name }}.*:ALL'
  state: 'present'


# --------------------------
#   PHP configuration
# --------------------------

wordpress_php5_pool:
  enabled: True
  name: 'wordpress'
  user: '{{ wordpress_user }}'
  group: '{{ wordpress_group }}'
  pm_max_children: '{{ wordpress_php5_max_children }}'
  php_value:
    post_max_size: '{{ wordpress_php5_upload_size }}'
    upload_max_filesize: '{{ wordpress_php5_upload_size }}'


# --------------------------
#   nginx server configuration
# --------------------------

wordpress_server_backend:
  by_role: 'carlalexander.wordpress'
  enabled: True
  default: False
  type: 'php5'
  listen: [ '{{ wordpress_varnish_backend_port }}' ]
  ssl: False
  acme: False
  filename: '{{ wordpress_domain }}'
  name: '{{ wordpress_nginx_server_name }}'
  root: '{{ wordpress_root }}'

  options: |
    client_max_body_size  {{ wordpress_php5_upload_size }};
    gzip_comp_level 5;
    gzip_min_length 256;
    gzip_proxied any;
    gzip_vary on;
    gzip_types application/atom+xml
      application/javascript
      application/json
      application/ld+json
      application/manifest+json
      application/rdf+xml
      application/rss+xml
      application/schema+json
      application/vnd.geo+json
      application/vnd.ms-fontobject
      application/x-font-ttf
      application/x-javascript
      application/x-web-app-manifest+json
      application/xhtml+xml
      application/xml
      font/eot
      font/opentype
      image/bmp
      image/svg+xml
      image/vnd.microsoft.icon
      image/x-icon
      text/cache-manifest
      text/css
      text/javascript
      text/plain
      text/vcard
      text/vnd.rim.location.xloc
      text/vtt
      text/x-component
      text/x-cross-domain-policy
      text/xml;

    rewrite /wp-admin$ $scheme://$host$uri/ permanent;
    {% if wordpress_multisite and not wordpress_multisite_subdomains %}

    if (!-e $request_filename) {
      rewrite ^(/[^/]+)?(/wp-.*) $2 last;
      rewrite ^(/[^/]+)?(/.*\.php) $2 last;
    }
    {% endif %}

  location:
    '/': 'try_files $uri $uri/ /index.php?$args;'

    '~ /(\.|wp-config.php|readme.html|license.txt|wp-cli.local.yml|wp-cli.yml)': 'return 404;'

    '= /robots.txt': |
      access_log off;
      log_not_found off;
      try_files /robots.txt /index.php;

    '~* ^.+\.(css|js|ogg|ogv|svg|svgz|eot|otf|woff|mp4|ttf|rss|atom|jpg|jpeg|gif|png|ico|zip|tgz|gz|rar|bz2|doc|xls|exe|ppt|tar|mid|midi|wav|bmp|rtf)$': |
      access_log off;
      expires max;
      add_header Cache-Control "public";

  location_allow:
    '/': '{{ wordpress_nginx_allow }}'

  php5: 'php'

  php5_options: |
    {% if wordpress_allow is defined and wordpress_allow %}
      {% for address in wordpress_allow %}
    allow {{ address }};
      {% endfor %}
    deny all;
    {% endif %}
    set $php_https off;

    if ($http_x_forwarded_proto = "https") {
      set $php_https on;
    }

    fastcgi_param HTTPS $php_https;
    fastcgi_next_upstream error timeout invalid_header http_500;

wordpress_server_varnish:
  by_role: 'carlalexander.wordpress'
  type: 'proxy'
  enabled: True
  default: False
  filename: 'varnish.{{ wordpress_domain }}'
  name: '{{ wordpress_nginx_server_name }}'
  listen: [ '80' ]
  listen_ssl: [ '443' ]
  ssl: '{{ wordpress_ssl }}'
  acme: False
  pki_crt: '{{ wordpress_nginx_crt }}'
  pki_key: '{{ wordpress_nginx_key }}'
  deny_hidden: False
  favicon: False
  proxy_pass: 'http://varnish'

  options: |
    client_max_body_size  {{ wordpress_php5_upload_size }};


# --------------------------
#   SSL configuration
# --------------------------

wordpress_ssl_files:
  - src: '{{ wordpress_ssl_crt }}'
    dest: '{{ wordpress_nginx_crt }}'

  - src: '{{ wordpress_ssl_key }}'
    dest: '{{ wordpress_nginx_key }}'


# --------------------------
#   nginx upstream configuration
# --------------------------

wordpress_upstream_php:
  enabled: True
  name: 'php'
  server:
   - 'unix:/var/run/hhvm/hhvm.sock'
   - 'unix:/var/run/php5-fpm-wordpress.sock backup'

wordpress_upstream_varnish:
  enabled: True
  name: 'varnish'
  server:
   - '127.0.0.1:{{ wordpress_varnish_listen }}'
   - '127.0.0.1:{{ wordpress_varnish_backend_port }} backup'


# --------------------------
#   Varnish configuration
# --------------------------

wordpress_varnish_backend:
  name: 'wordpress'
  port: '{{ wordpress_varnish_backend_port }}'
  probe: False
