---

# ---- MariaDB repository configuration ----

# MardiaDB keyserver fingerprint
mariadb_keyserver_fingerprint: '0xcbcb082a1bb943db'

# MariaDB Mirror location
mariadb_mirror: 'nyc2.mirrors.digitalocean.com'

# MariaDB version
mariadb_version: '10.0'

# ---- MariaDB server configuration ----

# Bind address of mysqld. If you want to allow access to the server over the
# network, change this to '0.0.0.0' (for all interfaces) or for specific IP
# address to bind on
mariadb_mysqld_bind_address: 'localhost'

# Default mysqld port to listen on
mariadb_mysqld_port: 3306

# This is a list of IP addresses or CIDR networks allowed to connect to MariaDB
# server from remote hosts. It will be applied in firewall (ferm) and
# /etc/hosts.allow (tcpwrappers).
# You will need to set mariadb_mysqld_bind_address to 0.0.0.0 and restart MariaDB
# server for it to listen on all network interfaces.
mariadb_mysqld_allow: []

# Maximum number of allowed connections
mariadb_mysqld_max_connections: 100

# Use this hash variable to set additional mysqld options
mariadb_mysqld_options: {}
#  'key_buffer': '16M'
#  'skip-name-resolve':

# List of additional system groups to append to the MariaDB system user
# 'ssl-cert' group is required for access to certificate private keys
mariadb_mysqld_append_groups: [ 'ssl-cert' ]


# ---- Encrypted connections ----

# Enable or disable support for TLS in MariaDB (using debops.pki)
mariadb_pki: True

# Base path for PKI directory
mariadb_pki_path: '{% if (ansible_local is defined and ansible_local.pki is defined) %}{{ ansible_local.pki.base_path }}{% else %}/etc/pki{% endif %}'

# Default PKI realm used by MariaDB (Debian MariaDB packages do not support chained
# certificates, see Debian Bug #630625)
mariadb_pki_realm: 'service'

# Default CA, certificate and private key used by MariaDB, relative to
# 'mariadb_pki_realm' variable
mariadb_pki_ca: 'CA.crt'
mariadb_pki_crt: 'default.crt'
mariadb_pki_key: 'default.key'

# Cipher suite used for encrypted connections
mariadb_pki_cipher: 'DHE-RSA-AES256-SHA'


# ---- PHPMyAdmin support ----

# Enable PHPMyAdmin? It will be installed on localhost with php5-fpm and nginx
# See 'phpmyadmin' role for more configuration options
mariadb_phpmyadmin: False


# ---- automysqlbackup configuration ----

# Mail address to send messages to (account or alias name will be properly
# routed by the Postfix SMTP server)
mariadb_backup_mailaddr: 'backup'

# Specify the day of the week to create weekly backups (1 - Monday, 7 - Sunday)
mariadb_backup_doweekly: '6'

# Don't keep copies of most recent backups by default
mariadb_backup_latest: 'no'


# ---- MariaDB databases and user accounts ----

# List of MariaDB databases to manage
mariadb_databases: []
  #- name: 'database_name'
  #  state: 'present,absent'        # optional

# Length of randomly generated passwords (it's a string)
mariadb_password_length: '20'

# Password for MariaDB root user
mariadb_root_password: "{{ lookup('password', secret + '/credentials/' + ansible_fqdn + '/mariadb/root/password length=' + mariadb_password_length) }}"

# List of MariaDB users to manage (defaults first)
mariadb_users: []
  #- name: 'user_name'              # required
  #  host: 'localhost'
  #  state: 'present,absent'
  #  password: ''                   # if not specified, random will be generated
  #                                 # and saved in the 'secret' storage
  #  priv: 'user_name.*:ALL'
  #  append_privs: 'no,yes'
