---

dependencies:

  - role: debops.secret

  - role: debops.ferm
    ferm_input_list:

      - type: 'dport_accept'
        dport: [ 'mysql' ]
        saddr: '{{ mariadb_mysqld_allow }}'
        weight: '50'
        filename: 'mysql_dependency_accept'

  - role: debops.tcpwrappers
    tcpwrappers_allow:

      - daemon: 'mysqld'
        client: '{{ mariadb_mysqld_allow }}'
        weight: '50'
        filename: 'mysql_dependency_allow'
        comment: 'Allow remote connections to MySQL server'
