---

- name: Create wp-cli source directory
  file:
    path: '{{ wpcli_src_dir }}'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'
  when: wpcli_installation_method == 'package'

- name: Get filename of latest wp-cli package version
  uri:
    url: '{{ wpcli_base_url }}/deb/php-wpcli_latest_all.deb'
    return_content: yes
  register: wpcli_wp_cli_package
  when: wpcli_installation_method == 'package'
  tags: [ 'role::wpcli:install' ]

- name: Download latest wp-cli package
  get_url:
    url: '{{ wpcli_base_url }}/deb/{{ wpcli_wp_cli_package.content }}'
    dest: '{{ wpcli_src_dir }}/{{ wpcli_wp_cli_package.content }}'
    mode: '0644'
    force: no
  when: wpcli_installation_method == 'package'
  tags: [ 'role::wpcli:install' ]

- name: Install wp-cli package
  apt:
    deb: '{{ wpcli_src_dir }}/{{ wpcli_wp_cli_package.content }}'
    state: 'present'
  when: wpcli_installation_method == 'package'
  tags: [ 'role::wpcli:install' ]

- name: Download wp-cli
  get_url:
    url: '{{ wpcli_base_url }}/phar/wp-cli.phar'
    dest: '{{ wpcli_bin_dir }}/wp'
    mode: '0755'
    force: 'yes'
  when: wpcli_installation_method == 'download'
  tags: [ 'role::wpcli:install' ]
